// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type HostnameInitParameters struct {
	Certificate *float64 `json:"certificate,omitempty" tf:"certificate,omitempty"`

	ContractID *string `json:"contractId,omitempty" tf:"contract_id,omitempty"`

	EdgeHostname *string `json:"edgeHostname,omitempty" tf:"edge_hostname,omitempty"`

	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	IPBehavior *string `json:"ipBehavior,omitempty" tf:"ip_behavior,omitempty"`

	ProductID *string `json:"productId,omitempty" tf:"product_id,omitempty"`

	// Email address that should receive updates on the IP behavior update request.
	StatusUpdateEmail []*string `json:"statusUpdateEmail,omitempty" tf:"status_update_email,omitempty"`

	// Enables to set timeout for processing
	Timeouts []TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// A JSON encoded list of use cases
	UseCases *string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type HostnameObservation struct {
	Certificate *float64 `json:"certificate,omitempty" tf:"certificate,omitempty"`

	ContractID *string `json:"contractId,omitempty" tf:"contract_id,omitempty"`

	EdgeHostname *string `json:"edgeHostname,omitempty" tf:"edge_hostname,omitempty"`

	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IPBehavior *string `json:"ipBehavior,omitempty" tf:"ip_behavior,omitempty"`

	ProductID *string `json:"productId,omitempty" tf:"product_id,omitempty"`

	// Email address that should receive updates on the IP behavior update request.
	StatusUpdateEmail []*string `json:"statusUpdateEmail,omitempty" tf:"status_update_email,omitempty"`

	// Enables to set timeout for processing
	Timeouts []TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// A JSON encoded list of use cases
	UseCases *string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type HostnameParameters struct {

	// +kubebuilder:validation:Optional
	Certificate *float64 `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// +kubebuilder:validation:Optional
	ContractID *string `json:"contractId,omitempty" tf:"contract_id,omitempty"`

	// +kubebuilder:validation:Optional
	EdgeHostname *string `json:"edgeHostname,omitempty" tf:"edge_hostname,omitempty"`

	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// +kubebuilder:validation:Optional
	IPBehavior *string `json:"ipBehavior,omitempty" tf:"ip_behavior,omitempty"`

	// +kubebuilder:validation:Optional
	ProductID *string `json:"productId,omitempty" tf:"product_id,omitempty"`

	// Email address that should receive updates on the IP behavior update request.
	// +kubebuilder:validation:Optional
	StatusUpdateEmail []*string `json:"statusUpdateEmail,omitempty" tf:"status_update_email,omitempty"`

	// Enables to set timeout for processing
	// +kubebuilder:validation:Optional
	Timeouts []TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// A JSON encoded list of use cases
	// +kubebuilder:validation:Optional
	UseCases *string `json:"useCases,omitempty" tf:"use_cases,omitempty"`
}

type TimeoutsInitParameters struct {
	Default *string `json:"default,omitempty" tf:"default,omitempty"`
}

type TimeoutsObservation struct {
	Default *string `json:"default,omitempty" tf:"default,omitempty"`
}

type TimeoutsParameters struct {

	// +kubebuilder:validation:Optional
	Default *string `json:"default,omitempty" tf:"default,omitempty"`
}

// HostnameSpec defines the desired state of Hostname
type HostnameSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     HostnameParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider HostnameInitParameters `json:"initProvider,omitempty"`
}

// HostnameStatus defines the observed state of Hostname.
type HostnameStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        HostnameObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Hostname is the Schema for the Hostnames API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,akamai}
type Hostname struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.contractId) || (has(self.initProvider) && has(self.initProvider.contractId))",message="spec.forProvider.contractId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.edgeHostname) || (has(self.initProvider) && has(self.initProvider.edgeHostname))",message="spec.forProvider.edgeHostname is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.groupId) || (has(self.initProvider) && has(self.initProvider.groupId))",message="spec.forProvider.groupId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipBehavior) || (has(self.initProvider) && has(self.initProvider.ipBehavior))",message="spec.forProvider.ipBehavior is a required parameter"
	Spec   HostnameSpec   `json:"spec"`
	Status HostnameStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// HostnameList contains a list of Hostnames
type HostnameList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Hostname `json:"items"`
}

// Repository type metadata.
var (
	Hostname_Kind             = "Hostname"
	Hostname_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Hostname_Kind}.String()
	Hostname_KindAPIVersion   = Hostname_Kind + "." + CRDGroupVersion.String()
	Hostname_GroupVersionKind = CRDGroupVersion.WithKind(Hostname_Kind)
)

func init() {
	SchemeBuilder.Register(&Hostname{}, &HostnameList{})
}
