//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Resource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInitParameters) DeepCopyInto(out *ResourceInitParameters) {
	*out = *in
	if in.AggregationType != nil {
		in, out := &in.AggregationType, &out.AggregationType
		*out = new(string)
		**out = **in
	}
	if in.ConstrainedProperty != nil {
		in, out := &in.ConstrainedProperty, &out.ConstrainedProperty
		*out = new(string)
		**out = **in
	}
	if in.DecayRate != nil {
		in, out := &in.DecayRate, &out.DecayRate
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.HostHeader != nil {
		in, out := &in.HostHeader, &out.HostHeader
		*out = new(string)
		**out = **in
	}
	if in.LeaderString != nil {
		in, out := &in.LeaderString, &out.LeaderString
		*out = new(string)
		**out = **in
	}
	if in.LeastSquaresDecay != nil {
		in, out := &in.LeastSquaresDecay, &out.LeastSquaresDecay
		*out = new(float64)
		**out = **in
	}
	if in.LoadImbalancePercentage != nil {
		in, out := &in.LoadImbalancePercentage, &out.LoadImbalancePercentage
		*out = new(float64)
		**out = **in
	}
	if in.MaxUMultiplicativeIncrement != nil {
		in, out := &in.MaxUMultiplicativeIncrement, &out.MaxUMultiplicativeIncrement
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceInstance != nil {
		in, out := &in.ResourceInstance, &out.ResourceInstance
		*out = make([]ResourceInstanceInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpperBound != nil {
		in, out := &in.UpperBound, &out.UpperBound
		*out = new(float64)
		**out = **in
	}
	if in.WaitOnComplete != nil {
		in, out := &in.WaitOnComplete, &out.WaitOnComplete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInitParameters.
func (in *ResourceInitParameters) DeepCopy() *ResourceInitParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInstanceInitParameters) DeepCopyInto(out *ResourceInstanceInitParameters) {
	*out = *in
	if in.DatacenterID != nil {
		in, out := &in.DatacenterID, &out.DatacenterID
		*out = new(float64)
		**out = **in
	}
	if in.LoadObject != nil {
		in, out := &in.LoadObject, &out.LoadObject
		*out = new(string)
		**out = **in
	}
	if in.LoadObjectPort != nil {
		in, out := &in.LoadObjectPort, &out.LoadObjectPort
		*out = new(float64)
		**out = **in
	}
	if in.LoadServers != nil {
		in, out := &in.LoadServers, &out.LoadServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UseDefaultLoadObject != nil {
		in, out := &in.UseDefaultLoadObject, &out.UseDefaultLoadObject
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInstanceInitParameters.
func (in *ResourceInstanceInitParameters) DeepCopy() *ResourceInstanceInitParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceInstanceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInstanceObservation) DeepCopyInto(out *ResourceInstanceObservation) {
	*out = *in
	if in.DatacenterID != nil {
		in, out := &in.DatacenterID, &out.DatacenterID
		*out = new(float64)
		**out = **in
	}
	if in.LoadObject != nil {
		in, out := &in.LoadObject, &out.LoadObject
		*out = new(string)
		**out = **in
	}
	if in.LoadObjectPort != nil {
		in, out := &in.LoadObjectPort, &out.LoadObjectPort
		*out = new(float64)
		**out = **in
	}
	if in.LoadServers != nil {
		in, out := &in.LoadServers, &out.LoadServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UseDefaultLoadObject != nil {
		in, out := &in.UseDefaultLoadObject, &out.UseDefaultLoadObject
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInstanceObservation.
func (in *ResourceInstanceObservation) DeepCopy() *ResourceInstanceObservation {
	if in == nil {
		return nil
	}
	out := new(ResourceInstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceInstanceParameters) DeepCopyInto(out *ResourceInstanceParameters) {
	*out = *in
	if in.DatacenterID != nil {
		in, out := &in.DatacenterID, &out.DatacenterID
		*out = new(float64)
		**out = **in
	}
	if in.LoadObject != nil {
		in, out := &in.LoadObject, &out.LoadObject
		*out = new(string)
		**out = **in
	}
	if in.LoadObjectPort != nil {
		in, out := &in.LoadObjectPort, &out.LoadObjectPort
		*out = new(float64)
		**out = **in
	}
	if in.LoadServers != nil {
		in, out := &in.LoadServers, &out.LoadServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UseDefaultLoadObject != nil {
		in, out := &in.UseDefaultLoadObject, &out.UseDefaultLoadObject
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceInstanceParameters.
func (in *ResourceInstanceParameters) DeepCopy() *ResourceInstanceParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceInstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceList) DeepCopyInto(out *ResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Resource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceList.
func (in *ResourceList) DeepCopy() *ResourceList {
	if in == nil {
		return nil
	}
	out := new(ResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceObservation) DeepCopyInto(out *ResourceObservation) {
	*out = *in
	if in.AggregationType != nil {
		in, out := &in.AggregationType, &out.AggregationType
		*out = new(string)
		**out = **in
	}
	if in.ConstrainedProperty != nil {
		in, out := &in.ConstrainedProperty, &out.ConstrainedProperty
		*out = new(string)
		**out = **in
	}
	if in.DecayRate != nil {
		in, out := &in.DecayRate, &out.DecayRate
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.HostHeader != nil {
		in, out := &in.HostHeader, &out.HostHeader
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LeaderString != nil {
		in, out := &in.LeaderString, &out.LeaderString
		*out = new(string)
		**out = **in
	}
	if in.LeastSquaresDecay != nil {
		in, out := &in.LeastSquaresDecay, &out.LeastSquaresDecay
		*out = new(float64)
		**out = **in
	}
	if in.LoadImbalancePercentage != nil {
		in, out := &in.LoadImbalancePercentage, &out.LoadImbalancePercentage
		*out = new(float64)
		**out = **in
	}
	if in.MaxUMultiplicativeIncrement != nil {
		in, out := &in.MaxUMultiplicativeIncrement, &out.MaxUMultiplicativeIncrement
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceInstance != nil {
		in, out := &in.ResourceInstance, &out.ResourceInstance
		*out = make([]ResourceInstanceObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpperBound != nil {
		in, out := &in.UpperBound, &out.UpperBound
		*out = new(float64)
		**out = **in
	}
	if in.WaitOnComplete != nil {
		in, out := &in.WaitOnComplete, &out.WaitOnComplete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceObservation.
func (in *ResourceObservation) DeepCopy() *ResourceObservation {
	if in == nil {
		return nil
	}
	out := new(ResourceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceParameters) DeepCopyInto(out *ResourceParameters) {
	*out = *in
	if in.AggregationType != nil {
		in, out := &in.AggregationType, &out.AggregationType
		*out = new(string)
		**out = **in
	}
	if in.ConstrainedProperty != nil {
		in, out := &in.ConstrainedProperty, &out.ConstrainedProperty
		*out = new(string)
		**out = **in
	}
	if in.DecayRate != nil {
		in, out := &in.DecayRate, &out.DecayRate
		*out = new(float64)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.HostHeader != nil {
		in, out := &in.HostHeader, &out.HostHeader
		*out = new(string)
		**out = **in
	}
	if in.LeaderString != nil {
		in, out := &in.LeaderString, &out.LeaderString
		*out = new(string)
		**out = **in
	}
	if in.LeastSquaresDecay != nil {
		in, out := &in.LeastSquaresDecay, &out.LeastSquaresDecay
		*out = new(float64)
		**out = **in
	}
	if in.LoadImbalancePercentage != nil {
		in, out := &in.LoadImbalancePercentage, &out.LoadImbalancePercentage
		*out = new(float64)
		**out = **in
	}
	if in.MaxUMultiplicativeIncrement != nil {
		in, out := &in.MaxUMultiplicativeIncrement, &out.MaxUMultiplicativeIncrement
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ResourceInstance != nil {
		in, out := &in.ResourceInstance, &out.ResourceInstance
		*out = make([]ResourceInstanceParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UpperBound != nil {
		in, out := &in.UpperBound, &out.UpperBound
		*out = new(float64)
		**out = **in
	}
	if in.WaitOnComplete != nil {
		in, out := &in.WaitOnComplete, &out.WaitOnComplete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceParameters.
func (in *ResourceParameters) DeepCopy() *ResourceParameters {
	if in == nil {
		return nil
	}
	out := new(ResourceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceSpec.
func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceStatus) DeepCopyInto(out *ResourceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceStatus.
func (in *ResourceStatus) DeepCopy() *ResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ResourceStatus)
	in.DeepCopyInto(out)
	return out
}
