name: akamai/akamai
resources:
    akamai:
        subCategory: ""
        description: akamai terrafrom provider.
        name: akamai
        title: akamai
        argumentDocs: {}
        importStatements: []
